module test_tb #(
    // target ("SIM", "GENERIC", "XILINX", "ALTERA")
    parameter TARGET = "GENERIC",
    //输入数据IO延时(如果为n,表示延时n*78ps) 
    parameter IDELAY_VALUE = 0,

    parameter AXI_ID_TX = 3,
    parameter AXI_ID_RX = 3,

    // Address width in bits
    parameter AXI_MAC_ADDR_W = 32,
    // ID width in bits
    parameter AXI_MAC_ID_W = 8,
    // Data width in bits
    parameter AXI_MAC_DATA_W = 64,

    // Address width in bits
    parameter AXI_REG_ADDR_W = 32,
    // ID width in bits
    parameter AXI_REG_ID_W = 8,
    // Data width in bits
    parameter AXI_REG_DATA_W = 32
)(
    input                               clk,
    input                               clk_200m,
    input                               enet_rst_n,
    output                              rst_n,

    output                              enet_gtx_clk,
    // input                               enet_grx_clk,
    output                              enet_rgmii_tx_ctl,
    output [3:0]                        enet_rgmii_txd,
    input                               enet_rgmii_rx_ctl,   
    input  [3:0]                        enet_rgmii_rxd,
    input                               enet_tx_clk,
    input                               enet_rx_clk,
    input                               enet_ref_clk,
    output [1:0]                        enet_txd,
    output                              enet_tx_en,
    output [1:0]                        enet_rmii_txd,
    output                              enet_rmii_tx_en,
    output                              enet_tx_er,
    input  [1:0]                        enet_rxd,
    input                               enet_rx_dv,
    input                               enet_rx_er,

    input                               enet_col,
    input                               enet_crs,

    output                              mdc,
    input                               mdi,
    output                              mdo,
    output                              mdo_en,

    input                               mst_awvalid,
    output                              mst_awready,
    input  [AXI_REG_ADDR_W    -1:0]     mst_awaddr,
    input  [8                 -1:0]     mst_awlen,
    input  [3                 -1:0]     mst_awsize,
    input  [2                 -1:0]     mst_awburst,
    input                               mst_awlock,
    input  [4                 -1:0]     mst_awcache,
    input  [3                 -1:0]     mst_awprot,
    input  [4                 -1:0]     mst_awqos,
    input  [4                 -1:0]     mst_awregion,
    input  [AXI_REG_ID_W      -1:0]     mst_awid,
    input                               mst_wvalid,
    output                              mst_wready,
    input                               mst_wlast,
    input  [AXI_REG_DATA_W    -1:0]     mst_wdata,
    input  [AXI_REG_DATA_W/8  -1:0]     mst_wstrb,
    output                              mst_bvalid,
    input                               mst_bready,
    output [AXI_REG_ID_W      -1:0]     mst_bid,
    output [2                 -1:0]     mst_bresp,
    input                               mst_arvalid,
    output                              mst_arready,
    input  [AXI_REG_ADDR_W    -1:0]     mst_araddr,
    input  [8                 -1:0]     mst_arlen,
    input  [3                 -1:0]     mst_arsize,
    input  [2                 -1:0]     mst_arburst,
    input                               mst_arlock,
    input  [4                 -1:0]     mst_arcache,
    input  [3                 -1:0]     mst_arprot,
    input  [4                 -1:0]     mst_arqos,
    input  [4                 -1:0]     mst_arregion,
    input  [AXI_REG_ID_W      -1:0]     mst_arid,
    output                              mst_rvalid,
    input                               mst_rready,
    output [AXI_REG_ID_W      -1:0]     mst_rid,
    output [2                 -1:0]     mst_rresp,
    output [AXI_REG_DATA_W    -1:0]     mst_rdata,
    output                              mst_rlast,

    output                              tx_clk,
    output                              tx_rst_n,
    output                              slv_tx_awvalid,
    input                               slv_tx_awready,
    output [AXI_MAC_ADDR_W    -1:0]     slv_tx_awaddr,
    output [8                 -1:0]     slv_tx_awlen,
    output [3                 -1:0]     slv_tx_awsize,
    output [2                 -1:0]     slv_tx_awburst,
    output                              slv_tx_awlock,
    output [4                 -1:0]     slv_tx_awcache,
    output [3                 -1:0]     slv_tx_awprot,
    output [4                 -1:0]     slv_tx_awqos,
    output [4                 -1:0]     slv_tx_awregion,
    output [AXI_MAC_ID_W      -1:0]     slv_tx_awid,
    output                              slv_tx_wvalid,
    input                               slv_tx_wready,
    output                              slv_tx_wlast, 
    output [AXI_MAC_DATA_W    -1:0]     slv_tx_wdata,
    output [AXI_MAC_DATA_W/8  -1:0]     slv_tx_wstrb,
    input                               slv_tx_bvalid,
    output                              slv_tx_bready,
    input  [AXI_MAC_ID_W      -1:0]     slv_tx_bid,
    input  [2                 -1:0]     slv_tx_bresp,
    output                              slv_tx_arvalid,
    input                               slv_tx_arready,
    output [AXI_MAC_ADDR_W    -1:0]     slv_tx_araddr,
    output [8                 -1:0]     slv_tx_arlen,
    output [3                 -1:0]     slv_tx_arsize,
    output [2                 -1:0]     slv_tx_arburst,
    output                              slv_tx_arlock,
    output [4                 -1:0]     slv_tx_arcache,
    output [3                 -1:0]     slv_tx_arprot,
    output [4                 -1:0]     slv_tx_arqos,
    output [4                 -1:0]     slv_tx_arregion,
    output [AXI_MAC_ID_W      -1:0]     slv_tx_arid,
    input                               slv_tx_rvalid,
    output                              slv_tx_rready,
    input  [AXI_MAC_ID_W      -1:0]     slv_tx_rid,
    input  [2                 -1:0]     slv_tx_rresp,
    input  [AXI_MAC_DATA_W    -1:0]     slv_tx_rdata,
    input                               slv_tx_rlast,

    output                              rx_clk,
    output                              rx_rst_n,
    output                              slv_rx_awvalid,
    input                               slv_rx_awready,
    output [AXI_MAC_ADDR_W    -1:0]     slv_rx_awaddr,
    output [8                 -1:0]     slv_rx_awlen,
    output [3                 -1:0]     slv_rx_awsize,
    output [2                 -1:0]     slv_rx_awburst,
    output                              slv_rx_awlock,
    output [4                 -1:0]     slv_rx_awcache,
    output [3                 -1:0]     slv_rx_awprot,
    output [4                 -1:0]     slv_rx_awqos,
    output [4                 -1:0]     slv_rx_awregion,
    output [AXI_MAC_ID_W      -1:0]     slv_rx_awid,
    output                              slv_rx_wvalid,
    input                               slv_rx_wready,
    output                              slv_rx_wlast, 
    output [AXI_MAC_DATA_W    -1:0]     slv_rx_wdata,
    output [AXI_MAC_DATA_W/8  -1:0]     slv_rx_wstrb,
    input                               slv_rx_bvalid,
    output                              slv_rx_bready,
    input  [AXI_MAC_ID_W      -1:0]     slv_rx_bid,
    input  [2                 -1:0]     slv_rx_bresp,
    output                              slv_rx_arvalid,
    input                               slv_rx_arready,
    output [AXI_MAC_ADDR_W    -1:0]     slv_rx_araddr,
    output [8                 -1:0]     slv_rx_arlen,
    output [3                 -1:0]     slv_rx_arsize,
    output [2                 -1:0]     slv_rx_arburst,
    output                              slv_rx_arlock,
    output [4                 -1:0]     slv_rx_arcache,
    output [3                 -1:0]     slv_rx_arprot,
    output [4                 -1:0]     slv_rx_arqos,
    output [4                 -1:0]     slv_rx_arregion,
    output [AXI_MAC_ID_W      -1:0]     slv_rx_arid,
    input                               slv_rx_rvalid,
    output                              slv_rx_rready,
    input  [AXI_MAC_ID_W      -1:0]     slv_rx_rid,
    input  [2                 -1:0]     slv_rx_rresp,
    input  [AXI_MAC_DATA_W    -1:0]     slv_rx_rdata,
    input                               slv_rx_rlast
);

wire [7:0] u_enet_txd;
assign enet_txd = u_enet_txd[1:0];

enet_core u_enet_core(
    .clk         (clk        ),
    .clk_200m    (clk_200m   ),
    .enet_rst_n  (enet_rst_n ),
    .rst_n       (rst_n      ),

    .enet_gtx_clk        ( enet_gtx_clk      ),
    .enet_rgmii_tx_ctl   ( enet_rgmii_tx_ctl ),
    .enet_rgmii_txd      ( enet_rgmii_txd    ),
    .enet_rgmii_rx_ctl   ( enet_rgmii_rx_ctl ),
    .enet_rgmii_rxd      ( enet_rgmii_rxd    ),
    .enet_tx_clk         ( enet_tx_clk       ),
    .enet_rx_clk         ( enet_rx_clk       ),
    .enet_ref_clk        ( enet_ref_clk      ),
    .enet_txd            ( u_enet_txd        ),
    .enet_tx_en          ( enet_tx_en        ),
    .enet_rmii_txd       ( enet_rmii_txd     ),
    .enet_rmii_tx_en     ( enet_rmii_tx_en   ),
    .enet_tx_er          ( enet_tx_er        ),
    .enet_rxd            ( {6'h0, enet_rxd}  ),
    .enet_rx_dv          ( enet_rx_dv        ),
    .enet_rx_er          ( enet_rx_er        ),

    .enet_col    (enet_col   ),
    .enet_crs    (enet_crs   ),

    .mdc     (mdc    ),
    .mdi     (mdi    ),
    .mdo     (mdo    ),
    .mdo_en  (mdo_en ),

    .mst_awvalid     (mst_awvalid    ),
    .mst_awready     (mst_awready    ),
    .mst_awaddr      (mst_awaddr     ),
    .mst_awlen       (mst_awlen      ),
    .mst_awsize      (mst_awsize     ),
    .mst_awburst     (mst_awburst    ),
    .mst_awlock      (mst_awlock     ),
    .mst_awcache     (mst_awcache    ),
    .mst_awprot      (mst_awprot     ),
    .mst_awqos       (mst_awqos      ),
    .mst_awregion    (mst_awregion   ),
    .mst_awid        (mst_awid       ),
    .mst_wvalid      (mst_wvalid     ),
    .mst_wready      (mst_wready     ),
    .mst_wlast       (mst_wlast      ),
    .mst_wdata       (mst_wdata      ),
    .mst_wstrb       (mst_wstrb      ),
    .mst_bvalid      (mst_bvalid     ),
    .mst_bready      (mst_bready     ),
    .mst_bid         (mst_bid        ),
    .mst_bresp       (mst_bresp      ),
    .mst_arvalid     (mst_arvalid    ),
    .mst_arready     (mst_arready    ),
    .mst_araddr      (mst_araddr     ),
    .mst_arlen       (mst_arlen      ),
    .mst_arsize      (mst_arsize     ),
    .mst_arburst     (mst_arburst    ),
    .mst_arlock      (mst_arlock     ),
    .mst_arcache     (mst_arcache    ),
    .mst_arprot      (mst_arprot     ),
    .mst_arqos       (mst_arqos      ),
    .mst_arregion    (mst_arregion   ),
    .mst_arid        (mst_arid       ),
    .mst_rvalid      (mst_rvalid     ),
    .mst_rready      (mst_rready     ),
    .mst_rid         (mst_rid        ),
    .mst_rresp       (mst_rresp      ),
    .mst_rdata       (mst_rdata      ),
    .mst_rlast       (mst_rlast      ),

    .tx_clk                  (tx_clk             ),
    .tx_rst_n                (tx_rst_n           ),
    .slv_tx_awvalid          (slv_tx_awvalid     ),
    .slv_tx_awready          (slv_tx_awready     ),
    .slv_tx_awaddr           (slv_tx_awaddr      ),
    .slv_tx_awlen            (slv_tx_awlen       ),
    .slv_tx_awsize           (slv_tx_awsize      ),
    .slv_tx_awburst          (slv_tx_awburst     ),
    .slv_tx_awlock           (slv_tx_awlock      ),
    .slv_tx_awcache          (slv_tx_awcache     ),
    .slv_tx_awprot           (slv_tx_awprot      ),
    .slv_tx_awqos            (slv_tx_awqos       ),
    .slv_tx_awregion         (slv_tx_awregion    ),
    .slv_tx_awid             (slv_tx_awid        ),
    .slv_tx_wvalid           (slv_tx_wvalid      ),
    .slv_tx_wready           (slv_tx_wready      ),
    .slv_tx_wlast            (slv_tx_wlast       ),
    .slv_tx_wdata            (slv_tx_wdata       ),
    .slv_tx_wstrb            (slv_tx_wstrb       ),
    .slv_tx_bvalid           (slv_tx_bvalid      ),
    .slv_tx_bready           (slv_tx_bready      ),
    .slv_tx_bid              (slv_tx_bid         ),
    .slv_tx_bresp            (slv_tx_bresp       ),
    .slv_tx_arvalid          (slv_tx_arvalid     ),
    .slv_tx_arready          (slv_tx_arready     ),
    .slv_tx_araddr           (slv_tx_araddr      ),
    .slv_tx_arlen            (slv_tx_arlen       ),
    .slv_tx_arsize           (slv_tx_arsize      ),
    .slv_tx_arburst          (slv_tx_arburst     ),
    .slv_tx_arlock           (slv_tx_arlock      ),
    .slv_tx_arcache          (slv_tx_arcache     ),
    .slv_tx_arprot           (slv_tx_arprot      ),
    .slv_tx_arqos            (slv_tx_arqos       ),
    .slv_tx_arregion         (slv_tx_arregion    ),
    .slv_tx_arid             (slv_tx_arid        ),
    .slv_tx_rvalid           (slv_tx_rvalid      ),
    .slv_tx_rready           (slv_tx_rready      ),
    .slv_tx_rid              (slv_tx_rid         ),
    .slv_tx_rresp            (slv_tx_rresp       ),
    .slv_tx_rdata            (slv_tx_rdata       ),
    .slv_tx_rlast            (slv_tx_rlast       ),

    .rx_clk                     (rx_clk             ),
    .rx_rst_n                   (rx_rst_n           ),
    .slv_rx_awvalid             (slv_rx_awvalid     ),
    .slv_rx_awready             (slv_rx_awready     ),
    .slv_rx_awaddr              (slv_rx_awaddr      ),
    .slv_rx_awlen               (slv_rx_awlen       ),
    .slv_rx_awsize              (slv_rx_awsize      ),
    .slv_rx_awburst             (slv_rx_awburst     ),
    .slv_rx_awlock              (slv_rx_awlock      ),
    .slv_rx_awcache             (slv_rx_awcache     ),
    .slv_rx_awprot              (slv_rx_awprot      ),
    .slv_rx_awqos               (slv_rx_awqos       ),
    .slv_rx_awregion            (slv_rx_awregion    ),
    .slv_rx_awid                (slv_rx_awid        ),
    .slv_rx_wvalid              (slv_rx_wvalid      ),
    .slv_rx_wready              (slv_rx_wready      ),
    .slv_rx_wlast               (slv_rx_wlast       ),
    .slv_rx_wdata               (slv_rx_wdata       ),
    .slv_rx_wstrb               (slv_rx_wstrb       ),
    .slv_rx_bvalid              (slv_rx_bvalid      ),
    .slv_rx_bready              (slv_rx_bready      ),
    .slv_rx_bid                 (slv_rx_bid         ),
    .slv_rx_bresp               (slv_rx_bresp       ),
    .slv_rx_arvalid             (slv_rx_arvalid     ),
    .slv_rx_arready             (slv_rx_arready     ),
    .slv_rx_araddr              (slv_rx_araddr      ),
    .slv_rx_arlen               (slv_rx_arlen       ),
    .slv_rx_arsize              (slv_rx_arsize      ),
    .slv_rx_arburst             (slv_rx_arburst     ),
    .slv_rx_arlock              (slv_rx_arlock      ),
    .slv_rx_arcache             (slv_rx_arcache     ),
    .slv_rx_arprot              (slv_rx_arprot      ),
    .slv_rx_arqos               (slv_rx_arqos       ),
    .slv_rx_arregion            (slv_rx_arregion    ),
    .slv_rx_arid                (slv_rx_arid        ),
    .slv_rx_rvalid              (slv_rx_rvalid      ),
    .slv_rx_rready              (slv_rx_rready      ),
    .slv_rx_rid                 (slv_rx_rid         ),
    .slv_rx_rresp               (slv_rx_rresp       ),
    .slv_rx_rdata               (slv_rx_rdata       ),
    .slv_rx_rlast               (slv_rx_rlast       )
);

endmodule //test_tb
